### ISSUE TITLE
Obtaining PL/SQL Table return from function call

### ISSUE THREAD

**Issue by rafaelmdbr** [go-goracle/goracle#143]
I'm trying to integrate some legacy Oracle PL/SQL code with go using goracle, but i'm not sure if PL/SQL tables are supported by goracle and the underlying driver.

I've seen some similar issues with cursors and other types (#117, #91), but had no success replicating their solutions.

PL/SQL

```
 FUNCTION fc_rec_agregacoes_nidx (wp_tipo IN NUMBER)
 RETURN pk_judi_estrutura_dados.tp_tb_rc_agregacao_nidx;
...
 TYPE tp_tb_rc_agregacao_nidx IS TABLE OF pk_judi_estrutura_dados.tp_rc_agregacao;

 TYPE tp_rc_agregacao IS RECORD(
        agpd_tcp_cd           judi_agrega_cred_p_dcomps.agpd_tcp_cd%TYPE,
        --tcp_tx_descricao      pdcomp_tp_cred_perdcomps.tcp_tx_descricao%TYPE,
        rv_meaning            cg_ref_codes.rv_meaning%TYPE,
        --tcp_dt_fim_vigencia   pdcomp_tp_cred_perdcomps.tcp_dt_fim_vigencia%TYPE,
        agpd_agre_cd	        judi_agrega_cred_p_dcomps.agpd_agre_cd%TYPE,
        agre_nm		            agregacoes.agre_nm%TYPE,
        agre_dt_extincao      agregacoes.agre_dt_extincao%TYPE,
        agpd_b_dt_inclusao    judi_agrega_cred_p_dcomps.agpd_b_dt_inclusao%TYPE
    );
```
go:
```
var result interface{}
_, err = db.ExecContext(ctx, `begin :result := pk_judi_cadastro_manter_tabela.fc_rec_agregacoes(1); end;`,
		sql.Named("result", sql.Out{Dest: &result}))

if err != nil {
    fmt.Println("Error running query")
    fmt.Println(err)
    return
}
```
then I get:

```
Error running query
dpiStmt_execute(mode=32 arrLen=-1): ORA-06550: line 1, column 18:
PLS-00382: expression is of wrong type
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
```
changing the result type to driver.Rows also yields the same error.

Is it possible to capture this return type and get its data using goracle?

**Comment by tgulacsi** [comment]
You're right, goracle does not support receiving PL/SQL record types - because OCI does not allow sufh functionality.
But there's a workaround: define a variable for each field of the record.
For a table of records, it's a little bit more involved: define a slice for each field, and convert from the variables-with-tables-of-values to the table-of-records.

It's all automated and used in production in "github.com/tgulacsi/oracall" - it generates a server code for the given stored package's functions and procedures, and provides a gRPC server stub with Protocol Buffers .proto file.

Although it cannot convert EVERYTHING (table-of-table or record-field-as-table aren't supported),
it is quite usable, and even such complicated scenarios can be solved by serializing and deserializing XML.

**Comment by anthony-tuininga** [comment]
@tgulacsi, ODPI-C (and OCI) do support binding PL/SQL record types -- with Oracle Client 12.1 and higher. You have to use [this function](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_getObjectType) to get the type to pass in to the variable creation function. Let me know if you need more information.

**Comment by tgulacsi** [comment]
AFAIK that is for Oracle database type, not for pl/sql type (that only lives in stored package).

**Comment by anthony-tuininga** [comment]
Nope! That can also be used for PL/SQL records and index-by types as can be seen this [example](https://github.com/oracle/python-cx_Oracle/blob/master/samples/PLSQLRecord.py) for cx_Oracle.
