### ISSUE TITLE
govendor test +local failing with vendor/gopkg.in/goracle.v2/conn.go:20:10: fatal error: 'dpiImpl.h' file not found #include "dpiImpl.h"

### ISSUE THREAD

**Issue by chakrapani123** [go-goracle/goracle#155]
go version
go version go1.11.5 darwin/amd64

error message:

vendor/gopkg.in/goracle.v2/conn.go:20:10: fatal error: 'dpiImpl.h' file not found
#include "dpiImpl.h"
         ^~~~~~~~~~~

**Comment by tgulacsi** [comment]
Vendor the C files under odpi dir, too!




On Mon, May 6, 2019 at 9:39 PM +0200, "chakrapani123" <notifications@github.com> wrote:












chakri-work:cpp-oracle-service cvelug200$ go version

go version go1.11.5 darwin/amd64


error message:


vendor/gopkg.in/goracle.v2/conn.go:20:10: fatal error: 'dpiImpl.h' file not found

#include "dpiImpl.h"

^~~~~~~~~~~

**Comment by mxplusb** [comment]
I ran into this as well, I'm not at all familiar with how Oracle drivers work. Here's what I did:

* Downloaded the ["basic"](http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html) version, not basic lite
*Extracted all of the shared object files in the zip file to and placed it under `/abs/path/project/vendor/include/oracle/`
* Set `CGO_CFLAGS="-I /abs/path/project/vendor/include/oracle"`
* `go install -v -buildmode pie .`

I still get the same error. Am I missing a step or placing things incorrectly?

**Comment by tgulacsi** [comment]
You've vendored goracle, but missed the "odpi" directory under goracle.v2, with its contents (embed, include and src dirs with .h and .c files).

**Comment by mxplusb** [comment]
@tgulacsi thanks for the hint, I found the problem!

For future folks, I had taken this as a dependency with go modules via `go get gopkg.in/goracle.v2`. It turns out that `go mod -vendor` [does not bring the entire tree](https://github.com/golang/go/issues/26366), only packages it sees fit. There was a tool that @nomad-software wrote called [vend](https://github.com/nomad-software/vend), which vendored the entire tree. Once the tree was vendored as you recommended, things worked as intended.

**Comment by mxplusb** [comment]
@tgulacsi thanks for the hint, I found the problem!

For future folks, I had taken this as a dependency with go modules via `go get gopkg.in/goracle.v2`. It turns out that `go mod -vendor` [does not bring the entire tree](https://github.com/golang/go/issues/26366), only packages it sees fit. There was a tool that @nomad-software wrote called [vend](https://github.com/nomad-software/vend), which vendored the entire tree. Once the tree was vendored as you recommended, things worked as intended.
