### ISSUE TITLE
Build errors for Linux 32-bit

### ISSUE THREAD

**Issue by gotoel** [go-goracle/goracle#197]
**Describe the bug**
Receiving the following error:

```
# gopkg.in/goracle.v2
../src/gopkg.in/goracle.v2/drv_10.go:32:2: undefined: ConnectionParams
../src/gopkg.in/goracle.v2/drv_10.go:33:2: undefined: drv
```

When building with the following command:
```
GOOS=linux GOARCH=386 go build -o /tmp/client1/foo1 client1/client_one.go
```

**To Reproduce**
1. Create a test project utilizing goracle
2. Perform build with the command specified above.

**Expected behavior**
Build succeeds, just like it does when running a 64bit build with the following command:
```
GOOS=linux GOARCH=amd64 go build -o /tmp/client1/foo1 client1/client_one.go
```

**Screenshots**
-

**Your oracle client version**
-

**Your goracle version**
Latest

**Your go version**
1.11.5

**Your gcc version**
-

**Machine (please complete the following information):**
 - OS: Linux
 - Architecture x86

**Additional context**
-

**Comment by tgulacsi** [comment]
Try with CGO=1, but AFAIK cross-compilation needs a proper C cross compiler, which is not easy.




On Tue, Sep 24, 2019 at 11:42 PM +0200, "gotoel" <notifications@github.com> wrote:












Describe the bug

Receiving the following error:
# gopkg.in/goracle.v2
../src/gopkg.in/goracle.v2/drv_10.go:32:2: undefined: ConnectionParams
../src/gopkg.in/goracle.v2/drv_10.go:33:2: undefined: drv



When building with the following command:
GOOS=linux GOARCH=386 go build -o /tmp/client1/foo1 client1/client_one.go



To Reproduce

Steps to reproduce the behavior:

Create a test project utilizing goracle
Perform build with the command specified above.



Expected behavior

Build succeeds, just like it does when running a 64bit build with the following command:
GOOS=linux GOARCH=amd64 go build -o /tmp/client1/foo1 client1/client_one.go

Screenshots
Your oracle client version


Your goracle version

Latest


Your go version

1.11.5
Your gcc version


Machine (please complete the following information):

OS: Linux
Architecture x86

Additional context

**Comment by gotoel** [comment]
Thanks for the info. CGO=1 did not work. Decided to just not ship 32bit for this particular project. This can be closed.
